version: '3.9'
services:
  db:
    container_name: express-toy-db
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - express-toy-db:/var/lib/postgresql/data
volumes:
  express-toy-db:
